AIRPORTS_UK_LIVERPOOL = "Liverpool John Lennon"
AIRPORTS_UK_BOURNREMOUTH = "Bournemouth International"
AIRPORTS_UK = {"LPL":AIRPORTS_UK_LIVERPOOL, "BOH": AIRPORTS_UK_BOURNREMOUTH}

AIRPORTS_OVERSEAS = {}
AIRCRAFT = {}

OVERSEAS_AIRPORT_CODE = 'Overseas airport code'
OVERSEAS_AIRPORT_NAME = 'Overseas airport name'

AIRCRAFT_TYPE = "Type"

AIRCRAFT_MEDIUM_NARROW = "Medium narrow body"
AIRCRAFT_MEDIUM_WIDE = "Medium wide body"
AIRCRAFT_LARGE_NARROW = "Large narrow body"
